### ISSUE TITLE
Can we have a new PyPI release?

### ISSUE THREAD

**Issue by ale-rt** [collective/collective.externaleditor#9]
Hi, I would like to have a new release for this package.
Probably a major one because master is breaking compatibility with older Plone and Python versions https://github.com/collective/collective.externaleditor/blob/679d73d7cb4d0bd19d9b34fb8252fb216a51937d/docs/HISTORY.rst

Can you please release it or add my user (`alert`) and the `collective` one as maintainers on PyPI?

Thanks a lot!

**Comment by flohcim** [comment]
Hi @ale-rt ! :heavy_check_mark: collective and you are now owners on PyPI! See ya!

**Comment by ale-rt** [comment]
Thanks :)
[Version 2.0.0 is out](https://pypi.org/project/collective.externaleditor/)!
See soon guys :)!
